[package]
name = "spyrun"
version = "1.0.0"
edition = "2021"

[dependencies]
aead = "0.5.2"
aes-gcm-siv = "0.11.1"
anyhow = "1.0.81"
base64 = "0.22.0"
chrono = "0.4.37"
clap = { version = "4.5.4", features = ["derive", "env", "cargo", "unicode"] }
crypto-hash = "0.3.4"
go-defer = "0.1.0"
log = "0.4.21"
log-derive = "0.4.1"
normalize-path = "0.2.1"
notify = "6.1.1"
path-slash = "0.2.1"
rand = "0.8.5"
rayon = "1.10.0"
regex = "1.10.4"
serde = { version = "1.0.197", features = ["derive"] }
single-instance = "0.3.3"
tera = "1.19.1"
time = { version = "0.3.34", features = ["macros", "local-offset"] }
toml = "0.8.12"
tracing = { version = "0.1.40", features = ["log", "attributes", "std", "tracing-attributes"] }
tracing-appender = "0.2.3"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["time", "json", "local-time", "env-filter"] }
walkdir = "2.5.0"
