# =============================================================================
# File        : rust-toolchain.toml
# Author      : yukimemi
# Last Change : 2023/10/24 06:28:06.
# =============================================================================

[toolchain]
channel = "nightly"
