[log]
path = "{{cwd}}/logs/{{cmd_stem}}.log"
level = "debug"

[all]

[[all.patterns]]
extension = "ps1"
cmd = "powershell"
arg = "-NoProfile -File {{input}}"

[[all.patterns]]
extension = "cmd"
cmd = "cmd"
arg = "/c {{input}}"

[[all.patterns]]
extension = "bat"
cmd = "cmd"
arg = "/c {{input}}"

[[spys]]
events = ["Create","Modify"]
input = "./in"
output = "./out"

[[spys.patterns]]
extension = "ps1"
cmd = "powershell"
arg = "-NoProfile -File {{input}}"

