[log]
path = "{{cwd}}/logs/{{cmd_stem}}.log"
level = "debug"

[[spys]]
name = "some1"

[[spys.patterns]]
extension = "ps1"
cmd = "powershell"
arg = ["-NoProfile", "-File", "{{input}}"]

[[spys]]
name = "some2"
events = ["Create","Modify"]
input = "./in2"
output = "./out2"

