[vars]
base_path = "/Users/yukimemi/src/github.com/yukimemi/spyrun"
version = "0.1.0"

[log]
path = "{{cwd}}/logs/{{cmd_stem}}.log"
level = "debug"

[[spys]]
name = "some1"
events = ["Modify"]

[[spys.patterns]]
pattern = "\\.ps1$"
cmd = "powershell"
arg = ["-NoProfile", "-File", "{{event_path}}"]
[[spys.patterns]]
pattern = "\\.sh$"
cmd = "bash"
arg = ["-c", "./{{input}}/{{env(name='SPYRUN_EXECUTE')}}.sh"]

[[spys]]
name = "some2"
events = ["Create","Modify"]
input = "{{base_path}}/in2"
output = "{{base_path}}/out2"

