[cfg]
stop = "./stop_spyrun.flg"

[vars]
base_path = "/tmp/spyrun"
version = "0.1.0"

[log]
path = "{{cwd}}/logs/{{cmd_stem}}.log"
level = "debug"

[[spys]]
name = "some1"
events = ["Modify"]

[[spys.patterns]]
pattern = "\\.ps1$"
cmd = "powershell"
arg = ["-NoProfile", "-File", "{{event_path}}"]
[[spys.patterns]]
pattern = "\\.sh$"
cmd = "bash"
arg = ["-c", "./{{input}}/{{env(name='SPYRUN_EXECUTE')}}.sh"]

[[spys]]
name = "some2"
events = ["Modify"]
input = "{{cfg_dir}}/in2"
output = "{{cfg_dir}}/out2"

[[spys]]
name = "some3"
events = ["Modify"]
input = "{{base_path}}/in2"
output = "{{base_path}}/out2"

