[cfg]
stop_flg = "./stop_spyrun.flg"

[vars]
base_path = "/tmp/spyrun"
version = "0.1.0"

[log]
path = "{{cwd}}/logs/{{cmd_stem}}.log"
level = "debug"

[[spys]]
name = "notify1"
events = ["Modify"]

[[spys.patterns]]
pattern = "\\.ps1$"
cmd = "powershell"
arg = ["-NoProfile", "-File", "{{event_path}}"]
[[spys.patterns]]
pattern = "\\.sh$"
cmd = "bash"
arg = ["-c", "./{{input}}/{{env(name='SPYRUN_EXECUTE')}}.sh"]

[[spys]]
name = "poll1"
events = ["Modify"]
input = "{{cfg_dir}}/in2"
output = "{{cfg_dir}}/out2"
delay = [1000, 10000]
[spys.poll]
interval = 1000

[[spys]]
name = "notify_with_scan"
events = ["Modify"]
input = "{{base_path}}/in2"
output = "{{base_path}}/out2"
[spys.walk]
match = ".*"
min_depth = 1
max_depth = 3

