# =============================================================================
# File        : test.toml
# Author      : yukimemi
# Last Change : 2025/03/08 21:12:58.
# =============================================================================

[vars]
version = '20250308_211258'

[cfg]
stop_flg = '{{ cfg_path }}'

[log]
path = '{{ cfg_dir }}\log\{{ cmd_stem }}.log'
level = 'warn'

[init]
cmd = 'powershell'
arg = ['-NoProfile', '-Command', '''& {
  echo '{{ version }}'
  echo '{{ cwd }}'
  Remove-Item -Force -Recurse -Filter "*.log" '{{ cwd }}\log'
  Remove-Item -Force -Recurse '{{ cwd }}\test'
  New-Item -Force -ItemType Directory '{{ cwd }}\test'
  "file1" | Set-Content -Encoding utf8 '{{ cwd }}\test\file1.txt'
  "file2" | Set-Content -Encoding utf8 '{{ cwd }}\test\file2.txt'
  "file3" | Set-Content -Encoding utf8 '{{ cwd }}\test\file3.txt'
  Remove-Item -Force -Recurse '{{ cwd }}\hoge'
}''']

[[spys]]
name = 'test found dir'
input = '{{ cfg_dir }}\test'
output = '{{ log_dir }}\{{ spy_name }}'
[spys.walk]
[[spys.patterns]]
pattern = '.*'
cmd = 'powershell'
arg = ['-NoProfile', '-Command', '''& {
  echo 'event_path: {{ event_path }}'
  echo 'event_kind: {{ event_kind }}'
}''']

[[spys]]
name = 'test not found dir'
input = '{{ cfg_dir }}\hoge'
output = '{{ log_dir }}\{{ spy_name }}'
[[spys.patterns]]
pattern = '.*'
cmd = 'powershell'
arg = ['-NoProfile', '-Command', '''& {
  echo 'event_path: {{ event_path }}'
  echo 'event_kind: {{ event_kind }}'
}''']
