# =============================================================================
# File        : test.toml
# Author      : yukimemi
# Last Change : 2024/12/22 23:32:05.
# =============================================================================

[vars]
version = '20241222_233205'

[cfg]
stop_flg = '{{ cfg_dir }}\stop.flg'

[log]
path = '{{ cfg_dir }}\log\{{ cmd_stem }}.log'
level = 'debug'

[init]
cmd = 'powershell'
arg = ['-NoProfile', '-Command', '''& {
  echo '{{ version }}'
}''']

[[spys]]
name = 'test found dir'
input = '{{ cfg_dir }}\test'
output = '{{ log_dir }}\{{ spy_name }}'
[spys.poll]
interval = 10000
[[spys.patterns]]
pattern = '.*'
cmd = 'powershell'
arg = ['-NoProfile', '-Command', '''& {
  echo 'event_path: {{ event_path }}'
  echo 'event_kind: {{ event_kind }}'
}''']

[[spys]]
name = 'test not found dir'
input = '{{ cfg_dir }}\hoge'
output = '{{ log_dir }}\{{ spy_name }}'
[[spys.patterns]]
pattern = '.*'
cmd = 'powershell'
arg = ['-NoProfile', '-Command', '''& {
  echo 'event_path: {{ event_path }}'
  echo 'event_kind: {{ event_kind }}'
}''']
